# Generated by Django 4.0.3 on 2022-04-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sub_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, max_length=190),
        ),
    ]
