# Generated by Django 4.0.3 on 2022-04-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_service_rename_sub_title_project_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
