# Generated by Django 4.0.3 on 2022-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(upload_to=''),
        ),
    ]
